import jsPDF from 'jspdf'
import { db, auth } from '../firebase'
import { ref, push, set } from 'firebase/database'

export const generateReport = async (type, data, dateRange, employeeName) => {
  const doc = new jsPDF()

  // Header
  doc.setFillColor(220, 38, 38)
  doc.rect(0, 0, 210, 25, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.text('Smart EMS — Report', 14, 16)

  // Report Info
  doc.setTextColor(0, 0, 0)
  doc.setFontSize(11)
  doc.setFont('helvetica', 'normal')
  doc.text(`Report Type  : ${type}`, 14, 35)
  doc.text(`Generated    : ${new Date().toLocaleDateString()}`, 14, 43)
  doc.text(`Date Range   : ${dateRange.from} — ${dateRange.to}`, 14, 51)
  if (employeeName) doc.text(`Employee     : ${employeeName}`, 14, 59)

  // Divider
  doc.setDrawColor(220, 38, 38)
  doc.line(14, 65, 196, 65)

  // Data
  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.text('Report Data:', 14, 75)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)

  let y = 85
  data.forEach((item, index) => {
    if (y > 270) {
      doc.addPage()
      y = 20
    }
    doc.text(`${index + 1}. ${item.title || item.name || 'N/A'}`, 14, y)
    doc.setTextColor(100, 100, 100)
    doc.text(`   Status: ${item.status || 'N/A'} | ${item.assignedToName || item.employeeName || ''}`, 14, y + 6)
    doc.setTextColor(0, 0, 0)
    y += 16
  })

  // Footer
  doc.setFontSize(9)
  doc.setTextColor(150, 150, 150)
  doc.text('Generated by Smart EMS', 14, 285)

  // PDF download karo
  const fileName = `SmartEMS_${type}_Report_${new Date().toLocaleDateString()}.pdf`
  doc.save(fileName)

  // Firebase mein save karo
  try {
    const reportRef = push(ref(db, 'reports'))
    await set(reportRef, {
      type,
      fileName,
      employeeName: employeeName || 'All Employees',
      dateFrom: dateRange.from,
      dateTo: dateRange.to,
      totalRecords: data.length,
      generatedBy: auth.currentUser?.email || 'Admin',
      generatedAt: Date.now(),
    })
  } catch (err) {
    console.error('Report save error:', err)
  }
}